export const category = [
  {
    name: "Hóa mỹ phẩm",
    params: "hoa-my-pham",
    children: [
      {
        name: "Chăm sóc da và tóc",
        params: "cham-soc-da-va-toc",
      },
    ],
  },
  {
    name: "Đồ sơ sinh",
    params: "do-so-sinh",
    children: [
      {
        name: "Đồ sơ sinh cần thiết",
        params: "do-so-sinh-can-thiet",
      },
    ],
  },
  {
    name: "Đồ sơ sinh",
    params: "do-so-sinh",
    children: [
      {
        name: "Đồ sơ sinh cần thiết",
        params: "do-so-sinh-can-thiet",
      },
    ],
  },
  {
    name: "Đồ sơ sinh",
    params: "do-so-sinh",
    children: [
      {
        name: "Đồ sơ sinh cần thiết",
        params: "do-so-sinh-can-thiet",
      },
    ],
  },
  {
    name: "Đồ sơ sinh",
    params: "do-so-sinh",
    children: [
      {
        name: "Đồ sơ sinh cần thiết",
        params: "do-so-sinh-can-thiet",
      },
    ],
  },
  {
    name: "Đồ sơ sinh",
    params: "do-so-sinh",
    children: [
      {
        name: "Đồ sơ sinh cần thiết",
        params: "do-so-sinh-can-thiet",
      },
    ],
  },
  {
    name: "Đồ sơ sinh",
    params: "do-so-sinh",
    children: [
      {
        name: "Đồ sơ sinh cần thiết",
        params: "do-so-sinh-can-thiet",
      },
    ],
  },
  {
    name: "Đồ sơ sinh",
    params: "do-so-sinh",
    children: [
      {
        name: "Đồ sơ sinh cần thiết",
        params: "do-so-sinh-can-thiet",
      },
    ],
  },
];

export const Products = [
  {
    name: "Bộ 06 khuôn cơm hình thú cho bé",
    price: "55 000",
    image: "https://cf.shopee.vn/file/f824c1fb08e397bc1425c20f19e7ab4e",
    state: true,
    material: "đang cập nhật",
    color: "đang cập nhật",
    size: "đang cập nhật",
    ingredient: "đang cập nhật",
    sold: 25,
    sale: {},
    evaluate: 5,
    type: "",
    typeName: "",
    childrenType: "",
    childrenTypeName: "",
    createdAt: "June 30, 2023 at 3:42:52 PM UTC+7",
  },
  {
    name: "Máy làm ấm khăn ướt",
    price: "320 000",
    image: "https://cdn.chanhtuoi.com/uploads/2021/01/may-lam-am-oidire.jpg",
    state: true,
    material: "đang cập nhật",
    color: "đang cập nhật",
    size: "đang cập nhật",
    ingredient: "đang cập nhật",
    sold: 28,
    sale: { newprice: "160 000", percent: "50" },
    evaluate: 5,
    type: "",
    typeName: "",
    childrenType: "",
    childrenTypeName: "",
    createdAt: "July 30, 2023 at 3:42:52 PM UTC+7",
  },
  {
    name: "Máy làm ấm khăn ướt",
    price: "320 000",
    image: "https://cdn.chanhtuoi.com/uploads/2021/01/may-lam-am-oidire.jpg",
    state: true,
    material: "đang cập nhật",
    color: "đang cập nhật",
    size: "đang cập nhật",
    ingredient: "đang cập nhật",
    sold: 28,
    sale: { newprice: "160 000", percent: "50" },
    evaluate: 5,
    type: "",
    typeName: "",
    childrenType: "",
    childrenTypeName: "",
    createdAt: "July 30, 2023 at 3:42:52 PM UTC+7",
  },
  {
    name: "Máy làm ấm khăn ướt",
    price: "320 000",
    image: "https://cdn.chanhtuoi.com/uploads/2021/01/may-lam-am-oidire.jpg",
    state: true,
    material: "đang cập nhật",
    color: "đang cập nhật",
    size: "đang cập nhật",
    ingredient: "đang cập nhật",
    sold: 28,
    sale: { newprice: "160 000", percent: "50" },
    evaluate: 5,
    type: "",
    typeName: "",
    childrenType: "",
    childrenTypeName: "",
    createdAt: "July 30, 2023 at 3:42:52 PM UTC+7",
  },
  {
    name: "Máy làm ấm khăn ướt",
    price: "320 000",
    image: "https://cdn.chanhtuoi.com/uploads/2021/01/may-lam-am-oidire.jpg",
    state: true,
    material: "đang cập nhật",
    color: "đang cập nhật",
    size: "đang cập nhật",
    ingredient: "đang cập nhật",
    sold: 28,
    sale: { newprice: "160 000", percent: "50" },
    evaluate: 5,
    type: "",
    typeName: "",
    childrenType: "",
    childrenTypeName: "",
    createdAt: "July 30, 2023 at 3:42:52 PM UTC+7",
  },
  {
    name: "Máy làm ấm khăn ướt",
    price: "320 000",
    image: "https://cdn.chanhtuoi.com/uploads/2021/01/may-lam-am-oidire.jpg",
    state: true,
    material: "đang cập nhật",
    color: "đang cập nhật",
    size: "đang cập nhật",
    ingredient: "đang cập nhật",
    sold: 28,
    sale: { newprice: "160 000", percent: "50" },
    evaluate: 5,
    type: "",
    typeName: "",
    childrenType: "",
    childrenTypeName: "",
    createdAt: "July 30, 2023 at 3:42:52 PM UTC+7",
  },
  {
    name: "Máy làm ấm khăn ướt",
    price: "320 000",
    image: "https://cf.shopee.vn/file/29343eb3773f0e5b5584cd36385fe477",
    state: true,
    material: "đang cập nhật",
    color: "đang cập nhật",
    size: "đang cập nhật",
    ingredient: "đang cập nhật",
    sold: 28,
    sale: { newprice: "160 000", percent: "50" },
    evaluate: 4,
    type: "",
    typeName: "",
    childrenType: "",
    childrenTypeName: "",
    createdAt: "July 30, 2023 at 3:42:52 PM UTC+7",
  },
];
